<script>
	import { enhance } from '$app/forms';
	import { invalidateAll } from '$app/navigation';
	import { showSuccess, showError } from '$lib/stores/toast.js';
	import Modal from '$lib/components/Modal.svelte';
	
	export let data;
	export let form;
	
	let selectedPlan = null;
	let isEditing = false;
	let isLoading = false;
	let searchTerm = '';
	let formErrors = {};
	let showModal = false;
	
	// Form input tracking for real-time display name generation
	let currentName = '';
	let currentDuration = '';
	
	$: plans = data.groupPlans || [];
	$: filteredPlans = plans.filter(plan => 
		plan.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
		(plan.display_name && plan.display_name.toLowerCase().includes(searchTerm.toLowerCase()))
	);
	
	// Real-time display name generation
	$: autoGeneratedDisplayName = generateDisplayName(currentName, currentDuration);
	
	function editPlan(plan) {
		selectedPlan = plan;
		isEditing = true;
		formErrors = {};
		// Update current form values for display name generation
		currentName = plan.name || '';
		currentDuration = plan.duration_days || '';
		showModal = true;
	}
	
	function newPlan() {
		selectedPlan = null;
		isEditing = false;
		formErrors = {};
		// Reset current form values
		currentName = '';
		currentDuration = '';
		showModal = true;
	}

	function closeModal() {
		showModal = false;
		selectedPlan = null;
		isEditing = false;
		formErrors = {};
		currentName = '';
		currentDuration = '';
	}
	
	function validateForm(formData) {
		const errors = {};
		const name = formData.get('name');
		const duration_days = formData.get('duration_days');
		const default_amount = formData.get('default_amount');

		// Name validation
		if (!name || !name.trim()) {
			errors.name = 'Plan name is required';
		}

		// Duration validation
		if (!duration_days || duration_days <= 0 || !Number.isInteger(Number(duration_days))) {
			errors.duration_days = 'This field is required';
		}

		// Default amount validation (optional field)
		if (default_amount && default_amount.toString().trim() !== '') {
			if (default_amount < 0 || isNaN(Number(default_amount))) {
				errors.default_amount = 'Default amount must be a positive number';
			}
		}

		// Display name uniqueness validation
		if (name && duration_days) {
			const generatedDisplayName = generateDisplayName(name.trim(), duration_days);
			const existingPlan = plans.find(plan => 
				plan.display_name === generatedDisplayName && 
				(!isEditing || plan.id !== selectedPlan?.id)
			);
			if (existingPlan) {
				errors.name = 'A plan with this name and duration already exists';
			}
		}

		return errors;
	}

	const submitForm = () => {
		return async ({ formData, result }) => {
			// Client-side validation
			const errors = validateForm(formData);
			if (Object.keys(errors).length > 0) {
				formErrors = errors;
				return;
			}

			isLoading = true;
			formErrors = {};

			if (result.type === 'success') {
				showSuccess(isEditing ? 'Plan updated successfully!' : 'Plan created successfully!');
				closeModal();
				await invalidateAll();
			} else if (result.type === 'failure') {
				showError(form?.error || 'Failed to save plan. Please try again.');
			}
			isLoading = false;
		};
	};
	
	function generateDisplayName(name, duration) {
		return name && duration ? `${name} - ${duration} days` : '';
	}
</script>

<svelte:head>
	<title>Plans - Kranos Gym</title>
</svelte:head>

<div class="plans-page">
	<div class="page-header">
		<div class="header-content">
			<h1 class="page-title animate-slide-up">
				Group Plans Management
			</h1>
			<p class="page-subtitle animate-slide-up">Create and manage gym membership plans</p>
		</div>
		<div class="header-actions animate-slide-up">
			<button class="btn btn-primary" on:click={newPlan}>
				<span class="btn-icon">➕</span>
				Add New Plan
			</button>
		</div>
	</div>


	<div class="plans-content">
		<div class="plans-list card animate-slide-up">
			<div class="card-header">
				<h2>
					<span class="section-icon">📋</span>
					Plans List
					<span class="plan-count">({filteredPlans.length})</span>
				</h2>
				<div class="search-container">
					<input
						type="text"
						placeholder="Search plans..."
						bind:value={searchTerm}
						class="search-input"
					/>
					<span class="search-icon">🔍</span>
				</div>
			</div>
			
			<div class="plans-table-container">
				{#if filteredPlans.length === 0}
					<div class="empty-state">
						<div class="empty-icon">💪</div>
						<h3>No Plans Found</h3>
						<p>Start by creating your first plan</p>
					</div>
				{:else}
					<table class="plans-table">
						<thead>
							<tr>
								<th>Display Name</th>
								<th>Plan Name</th>
								<th>Duration (Days)</th>
								<th>Default Amount (₹)</th>
								<th>Status</th>
								<th>Actions</th>
							</tr>
						</thead>
						<tbody>
							{#each filteredPlans as plan}
								<tr class="plan-row">
									<td class="plan-display-name">
										{plan.display_name}
									</td>
									<td class="plan-name">
										{plan.name}
									</td>
									<td class="plan-duration">
										{plan.duration_days}
									</td>
									<td class="plan-amount">
										₹{plan.default_amount || '-'}
									</td>
									<td class="plan-status">
										{#if plan.status === 'Active'}
											<span class="status-badge active">Active</span>
										{:else}
											<span class="status-badge inactive">Inactive</span>
										{/if}
									</td>
									<td class="plan-actions">
										<button 
											class="btn btn-secondary btn-sm"
											on:click={() => editPlan(plan)}
										>
											✏️ Edit
										</button>
									</td>
								</tr>
							{/each}
						</tbody>
					</table>
				{/if}
			</div>
		</div>
	</div>
</div>

<!-- Plan Modal -->
<Modal bind:show={showModal} title={isEditing ? 'Edit Plan' : 'Add New Plan'} on:close={closeModal}>
	<form 
		method="post" 
		action={isEditing ? '?/update' : '?/create'}
		use:enhance={submitForm}
		class="plan-form-content"
		novalidate
	>
		{#if isEditing}
			<input type="hidden" name="id" value={selectedPlan?.id} />
		{/if}

		<div class="form-group">
			<label for="name" class="form-label">Plan Name *</label>
			<input
				type="text"
				id="name"
				name="name"
				bind:value={currentName}
				class="form-control"
				class:error={formErrors.name}
				placeholder="e.g., MMA Focus, Boxing Basics"
				on:input={() => {
					if (formErrors.name) {
						formErrors = { ...formErrors, name: '' };
					}
				}}
			/>
			{#if formErrors.name}
				<span class="error-message">{formErrors.name}</span>
			{/if}
		</div>

		<div class="form-group">
			<label for="duration_days" class="form-label">Duration (Days) *</label>
			<input
				type="number"
				id="duration_days"
				name="duration_days"
				bind:value={currentDuration}
				class="form-control"
				class:error={formErrors.duration_days}
				placeholder="e.g., 30, 90, 180"
				on:input={() => {
					if (formErrors.duration_days) {
						formErrors = { ...formErrors, duration_days: '' };
					}
				}}
			/>
			{#if formErrors.duration_days}
				<span class="error-message">{formErrors.duration_days}</span>
			{/if}
		</div>

		<div class="form-group">
			<label for="default_amount" class="form-label">Default Amount (₹)</label>
			<input
				type="number"
				id="default_amount"
				name="default_amount"
				value={selectedPlan?.default_amount || ''}
				class="form-control"
				class:error={formErrors.default_amount}
				placeholder="e.g., 149.99"
				on:input={() => {
					if (formErrors.default_amount) {
						formErrors = { ...formErrors, default_amount: '' };
					}
				}}
			/>
			{#if formErrors.default_amount}
				<span class="error-message">{formErrors.default_amount}</span>
			{/if}
		</div>

		<div class="form-group">
			<label for="status" class="form-label">Status</label>
			<select
				id="status"
				name="status"
				class="form-control"
				value={selectedPlan?.status || 'Active'}
			>
				<option value="Active">Active</option>
				<option value="Inactive">Inactive</option>
			</select>
		</div>

		<div class="form-group">
			<label for="display_name" class="form-label">Display Name</label>
			<input type="hidden" name="display_name" value={autoGeneratedDisplayName} />
			<div class="form-control disabled">
				{autoGeneratedDisplayName || 'Auto-generated from plan name and duration'}
			</div>
			<small class="form-hint">Auto-generated: "Plan Name - X days"</small>
		</div>


		<div class="form-actions">
			<button 
				type="button" 
				class="btn btn-secondary"
				on:click={closeModal}
				disabled={isLoading}
			>
				Cancel
			</button>
			<button 
				type="submit" 
				class="btn btn-primary"
				disabled={isLoading}
			>
				{#if isLoading}
					<span class="loading-spinner"></span>
				{/if}
				<span class="btn-icon">{isEditing ? '💾' : '➕'}</span>
				{isEditing ? 'Update Plan' : 'Create Plan'}
			</button>
		</div>
	</form>
</Modal>

<style>
	.plans-page {
		max-width: 1200px;
		margin: 0 auto;
		padding: 2rem 1rem;
	}

	.page-header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		margin-bottom: 3rem;
		flex-wrap: wrap;
		gap: 1rem;
	}

	.header-content h1 {
		font-size: 2.5rem;
		font-weight: 700;
		margin-bottom: 0.5rem;
		background: var(--gradient-primary);
		-webkit-background-clip: text;
		-webkit-text-fill-color: transparent;
		background-clip: text;
	}


	.page-subtitle {
		color: var(--text-muted);
		font-size: 1.1rem;
		animation-delay: 0.2s;
	}

	.header-actions {
		animation-delay: 0.3s;
	}


	.plans-content {
		display: block;
		animation-delay: 0.5s;
	}

	.card-header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		margin-bottom: 1.5rem;
		padding-bottom: 1rem;
		border-bottom: 1px solid var(--border);
		flex-wrap: wrap;
		gap: 1rem;
	}

	.card-header h2 {
		display: flex;
		align-items: center;
		gap: 0.75rem;
		font-size: 1.5rem;
		font-weight: 600;
		margin: 0;
	}

	.section-icon {
		font-size: 1.5rem;
		filter: drop-shadow(0 0 10px var(--primary));
	}

	.plan-count {
		color: var(--text-muted);
		font-size: 1rem;
		font-weight: 400;
	}

	.search-container {
		position: relative;
		min-width: 200px;
	}

	.search-input {
		width: 100%;
		padding: 0.75rem 2.5rem 0.75rem 1rem;
		border: 1px solid var(--border);
		border-radius: 8px;
		background: var(--surface);
		color: var(--text);
		font-size: 0.9rem;
		transition: var(--transition-fast);
	}

	.search-input:focus {
		outline: none;
		border-color: var(--primary);
		box-shadow: 0 0 0 3px rgba(243, 148, 7, 0.2);
	}

	.search-icon {
		position: absolute;
		right: 0.75rem;
		top: 50%;
		transform: translateY(-50%);
		color: var(--text-muted);
		font-size: 1rem;
	}

	.plans-table-container {
		overflow-x: auto;
	}

	.empty-state {
		text-align: center;
		padding: 3rem 1rem;
		color: var(--text-muted);
	}

	.empty-icon {
		font-size: 4rem;
		margin-bottom: 1rem;
		opacity: 0.5;
	}

	.empty-state h3 {
		margin-bottom: 0.5rem;
		color: var(--text);
	}

	.plans-table {
		width: 100%;
		border-collapse: collapse;
		margin-top: 1rem;
	}

	.plans-table th,
	.plans-table td {
		padding: 1rem;
		text-align: left;
		border-bottom: 1px solid var(--border);
	}

	.plans-table th {
		background: var(--surface-light);
		font-weight: 600;
		color: var(--text);
		position: sticky;
		top: 0;
		z-index: 10;
		border-bottom: 2px solid var(--primary);
		box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
	}

	.plan-row {
		transition: var(--transition-fast);
	}

	.plan-row:hover {
		background: var(--gradient-glow);
	}

	.plan-name {
		font-weight: 600;
		color: var(--text);
	}

	.plan-display-name {
		font-weight: 600;
		color: var(--text);
	}

	.plan-duration {
		color: var(--text-muted);
	}

	.plan-amount {
		color: var(--text-muted);
		font-family: monospace;
	}

	.plan-actions {
		text-align: center;
	}

	.status-badge {
		padding: 0.25rem 0.5rem;
		border-radius: 12px;
		font-size: 0.75rem;
		font-weight: 500;
	}

	.status-badge.active {
		background: rgba(74, 222, 128, 0.2);
		color: var(--success);
		border: 1px solid var(--success);
	}

	.status-badge.inactive {
		background: rgba(239, 68, 68, 0.2);
		color: var(--error);
		border: 1px solid var(--error);
	}



	.btn-sm {
		padding: 0.5rem 1rem;
		font-size: 0.85rem;
	}

	.plan-form-content {
		display: flex;
		flex-direction: column;
		gap: 1.5rem;
	}

	.form-group {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
	}

	.form-label {
		font-weight: 600;
		color: var(--text);
		font-size: 0.9rem;
	}

	.form-hint {
		font-size: 0.8rem;
		color: var(--text-muted);
		font-style: italic;
	}

	.error-message {
		font-size: 0.85rem;
		color: var(--error);
		font-weight: 500;
		margin-top: 0.25rem;
	}

	.form-control.disabled {
		background: var(--bg-secondary);
		color: var(--text-muted);
		cursor: not-allowed;
		opacity: 0.7;
	}


	.form-actions {
		display: flex;
		gap: 1rem;
		flex-wrap: wrap;
	}

	.btn-icon {
		font-size: 1rem;
	}

	.loading-spinner {
		width: 16px;
		height: 16px;
		border: 2px solid transparent;
		border-top: 2px solid currentColor;
		border-radius: 50%;
		animation: spin 1s linear infinite;
	}


	@keyframes spin {
		0% { transform: rotate(0deg); }
		100% { transform: rotate(360deg); }
	}

	@media (max-width: 768px) {
		.plans-table-container {
			overflow-x: auto;
		}

		.plans-table {
			min-width: 600px;
		}

		.page-header {
			flex-direction: column;
			align-items: flex-start;
		}

		.card-header {
			flex-direction: column;
			align-items: flex-start;
		}

		.search-container {
			width: 100%;
		}

		.form-actions {
			flex-direction: column;
		}
	}
</style>