version: '3.8'

services:
  kranos-gym:
    build: .
    container_name: kranos-gym-app
    ports:
      - "3000:3000"
    volumes:
      # Mount local database directory for persistence
      - ./data:/app/data
      # Mount uploads directory for images
      - ./static/uploads:/app/static/uploads
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - DATABASE_URL=/app/data/kranos.db
      - ORIGIN=http://localhost:3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s